language: java

before_install:
  - cd cp

after_success:
  - >
    if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      mvn deploy --settings travis-config.xml -DskipTests=true -B
      mvn site --settings github-config.xml -B
    fi
