language: java

branches:
  only:
  - master

before_install:
  # Import decrypt and import gpg keys
  - >
    openssl aes-256-cbc
    -K $encrypted_4ba34fa7ea95_key  -iv $encrypted_4ba34fa7ea95_iv
    -in gpg-keys/secret.asc.enc -out gpg-keys/secret.asc -d
  - gpg --import gpg-keys/public.asc
  - gpg --import gpg-keys/secret.asc
  # Enter the maven project folder
  - cd cp

before_script:
  - mvn scala:doc -B # generate/test documentation

after_success:
  - >
    if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      mvn deploy --settings travis-config.xml -DskipTests=true -B
      mvn site --settings github-config.xml -B
    fi
