language: java

before_install:
  # Create temporary keypair
  - ssh-keygen -b 2048 -t rsa -f /tmp/sshkey -q -N ""
  - eval "$(ssh-agent -s)"
  - ssh-add /tmp/sshkey
  # Enter the maven project folder
  - cd cp

before_script:
  - mvn scala:doc -B # generate/test documentation

after_success:
  - >
    if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      mvn deploy --settings travis-config.xml -DskipTests=true -B
      mvn site --settings github-config.xml -B
    fi
